#!/bin/bash

TOKEN=$1
USER=sergeyitsib
CONFIG_FILE="dnsmasq-full/config.json"
VERSION=$(cat "$CONFIG_FILE" | grep --regexp='"version":' | cut -d '"' -f4)

echo "Build docker image v${VERSION}"
#sergeyitsib/image-{arch}-dnsmasq
docker run \
	--rm \
	--privileged \
	-v ~/.docker:/root/.docker \
	-v ./dnsmasq-full:/data \
	--platform linux/x86_64 \
	homeassistant/amd64-builder \
		--all \
		--addon \
		--target /data \
		--image image-{arch}-dnsmasq \
		--version "v${VERSION}" \
		--docker-hub "${USER}" \
		--docker-user "${USER}" \
		--docker-password "${TOKEN}"

