#!/bin/bash

TOKEN=$1
USER=sergeyitsib
CONFIG_FILE="dnsmasq-full/config.yaml"
VERSION=$(cat "$CONFIG_FILE" | grep --regexp='^version:' | cut -d ':' -f2 | sed -e 's/^[[:space:]]*//')

echo "Build docker image v${VERSION}"

docker run \
	--rm \
	--privileged \
	-v ~/.docker:/root/.docker \
	-v ./dnsmasq-full:/dnsmasq-full \
	--platform linux/x86_64 \
	homeassistant/amd64-builder \
		--all \
		--addon \
		--target /dnsmasq-full \
		--image image-{arch}-dnsmasq \
		--version "v${VERSION}" \
		--docker-hub "${USER}" \
		--docker-user "${USER}" \
		--docker-password "${TOKEN}"

