---
name: Dnsmasq Full
slug: dnsmasq-full
version: 1.6.20
description: Dnsmasq is a lightweight DNS, TFTP, PXE, router advertisement and DHCP server.
stage: experimental
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: sergeyitsib/image-{arch}-dnsmasq
url: https://github.com/itsib/dnsmasq
advanced: true
panel_icon: mdi:dns
map:
  - config:rw
privileged:
  - NET_ADMIN
apparmor: false
ingress: false
startup: system
init: false
host_network: true
ports:
  53/tcp: 53
  53/udp: 53
  67/udp: 67
options:
  data_path: "/config/dnsmasq_full"
schema:
  data_path: str
