name: Release

on:
  push:
    branches:
      - main

env:
  env_var: production

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    environment: production
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./dnsmasq-full"
  deploy:
    name: Build and publish
    needs: init
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

#      - name: Build the builder
#        uses: home-assistant/builder@master
#        with:
#          args: |
#            --test \
#            --amd64 \
#            --target ./dnsmasq-full
#
      - name: Test ${{ matrix.architecture }} builder
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.architecture }} \
            --target ./dnsmasq-full \
            --docker-hub ${{ vars.DOCKER_USERNAME }} \
            --image image-${{ matrix.architecture }}-dnsmasq
