name: "Test"

on: [push, pull_request]


jobs:
  build:
    name: Test action build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

#      - name: Build the builder
#        uses: home-assistant/builder@master
#        with:
#          args: |
#            --test \
#            --i386 \
#            --target /data \
#            --generic latest
      - name: Test ${{ matrix.arch }} builder
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --target /data \
            --generic ${{ github.sha }}
